name: fast_barcode_scanner_beeper
description: A common platform interface for the fast_barcode_scanner plugin.
homepage: https://github.com/jhoogstraat/fast_barcode_scanner/tree/master/fast_barcode_scanner_platform_interface
author: Joshua Hoogstraat
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_barcode_scanner:
    path: ../fast_barcode_scanner
  soundpool: ^1.1.3