name: fast_barcode_scanner_example
description: Demonstrates how to use the fast_barcode_scanner plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fast_barcode_scanner:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/